config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :new, :create, :show] do
    resources :goals, only: [:index]
  end
  resource :session, only: [:new, :create, :destroy]
  resources :goals, except: [:index]
  resources :comments, only: [:create, :destroy]
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :commentable, polymorphic: true
  belongs_to :user
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :name, :description, :user_id, presence: true
  validates :private, inclusion: { in: [true, false] }

  belongs_to :user,
    class_name: 'User',
    foreign_key: :user_id,
    primary_key: :id

  has_many :comments, as: :commentable

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :username, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token

  attr_reader :password

  has_many :goals,
    class_name: 'Goal',
    foreign_key: :user_id,
    primary_key: :id

  has_many :comments, as: :commentable

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)

    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
    self.session_token
  end

  def public_goals
    self.goals.select{ |goal| goal.private == false }
  end

  private
  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    current_user = User.find_by_session_token(session[:session_token])
    current_user.nil? ? nil : current_user
  end

  def logged_in?
    !!current_user
  end

  def login(user)
    session[:session_token] = user.reset_session_token!
  end

  def require_signed_in
    redirect_to new_session_url unless logged_in?
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      if @comment.commentable_type == "Goal"
        redirect_to goal_url(@comment.commentable_id)
      else
        redirect_to user_url(@comment.commentable_id)
      end
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to user_url(current_user)
    end
  end

  def destroy
  end

  private
  def comment_params
    params.require(:comment).permit(:comment, :commentable_id, :commentable_type)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  before_action :require_signed_in
  before_action :goal_owner?, only: [:edit, :update, :destroy]

  def index
    @user = User.find(params[:user_id])
    if @user == current_user
      @goals = @user.goals
    else
      @goals = @user.public_goals
    end
  end

  def new
    @goal = Goal.new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id

    if @goal.save
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def show
    @goal = Goal.find(params[:id])
    if @goal.user == current_user
      render :show
    elsif @goal.private == false
      render :show
    else
      flash[:errors] = "Private Goal"
      redirect_to user_url(current_user)
    end
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])

    if @goal.update(goal_params)
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy
    redirect_to user_goals_url(current_user)
  end

  private
  def goal_params
    params.require(:goal).permit(:name, :description, :private, :completed)
  end

  def goal_owner?
    @goal = Goal.find(params[:id])
    redirect_to user_url(current_user) unless current_user.id == @goal.user_id
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    @user = User.find_by_credentials(user_params[:username],
                                     user_params[:password])
    if @user
      login(@user)
      redirect_to users_url
    else
      flash.now[:errors] = "Invalid username/password"
      render :new
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_signed_in, only: [:show, :index]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    redirect_to user_goals_url(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:session_token] = @user.session_token
      redirect_to users_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    <<-HTML.html_safe
      <input type="hidden"
             name="authenticity_token"
             value="#{form_authenticity_token}">
       HTML
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_new.html.erb
<form action="<%= comments_url  %>" method="POST">
  <%= auth_token %>
  <label>Comment
    <textarea name="comment[comment]"></textarea>
  </label>
  <input type="hidden" name="comment[commentable_id]" value="<%= id %>">
  <input type="hidden" name="comment[commentable_type]" value="<%= type %>">
  <button value="submit">Add Comment</button>
</form>

app/views/goals/edit.html.erb
<h1>Edit Goal</h1>

<form action="<%= goal_url(@goal) %>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  <%= auth_token %>
  <label>Name
    <input type="text" name="goal[name]" value="<%= @goal.name %>">
  </label>
  <label>Description
    <input type="text" name="goal[description]" value="<%= @goal.description %>">
  </label>

  <label>Private
    <input type="radio" <% %> <%= "checked" if @goal.private %> name="goal[private]" value="true">
  </label>
  <label>Public
    <input type="radio" <% %> <%= "checked" unless @goal.private %> name="goal[private]" value="false">
  </label>
  <input type="hidden" name="goal[completed]" value="false">
  <label>Completed
    <input type="checkbox" <%  %><%= "checked" if @goal.completed %> name="goal[completed]" value="true">
  </label>
  <button value="submit">Edit Goal</button>
</form>

app/views/goals/index.html.erb
<h1><%= @user.username %>'s goals.</h1>

<% @goals.each do |goal| %>
<p>
  <%= goal.name %>
  <%= goal.description %>
  <%= goal.completed ? "Completed" : "Not Completed" %>
</p>
<p>
  <a href="<%= edit_goal_url(goal) %>">Edit</a>
  <form action="<%= goal_url(goal) %>" method="POST">
    <%= auth_token %>
    <input type="hidden" name="_method" value="DELETE">
    <button value="submit">Delete</button>
  </form>
</p>
<% end %>

<% if @user == current_user %>
  <a href="<%= new_goal_url %>">New Goal</a>
<% end %>

app/views/goals/new.html.erb
<h1>New Goal</h1>

<form action="<%= goals_url  %>" method="POST">
  <%= auth_token %>
  <label>Name
    <input type="text" name="goal[name]">
  </label>
  <label>Description
    <input type="text" name="goal[description]">
  </label>

  <label>Private
    <input type="radio" checked name="goal[private]" value="true">
  </label>
  <label>Public
    <input type="radio" name="goal[private]" value="false">
  </label>
  <input type="hidden" name="goal[completed]" value="false">
  <button value="submit">Create Goal</button>
</form>

app/views/goals/show.html.erb
<h1><%= @goal.user.username %>'s goal.</h1>
<p>
  <%= @goal.name %>
  <%= @goal.description %>
  <%= @goal.completed ? "Completed" : "Not Completed" %>
</p>
<% if current_user == @goal.user %>
<p>
  <a href="<%= edit_goal_url(@goal) %>">Edit</a>
  <form action="<%= goal_url(@goal) %>" method="POST">
    <%= auth_token %>
    <input type="hidden" name="_method" value="DELETE">
    <button value="submit">Delete</button>
  </form>
</p>
<% end %>

<% @goal.comments.each do |comment| %>
  <p><%= comment.comment %> by: <%= comment.user.username %></p>
<% end %>

<%= render 'comments/new', id: @goal.id, type: "Goal" %>


<a href=" <%= user_goals_url(@goal.user) %>">
Back to <%= @goal.user.username %>'s goals</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalMotivate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= flash[:errors] %>
<% if logged_in? %>
  <p>
    Username: <%= current_user.username %>
  </p>
  <form action="<%= session_url%>" method="POST">
    <%= auth_token %>
      <input type="hidden" name="_method" value="DELETE">
      <button value="submit">Log Out</button>
  </form>
  <a href="<%= user_url(current_user)%>">Home</a>
<% else %>
    <a href="<%= new_session_url %>"> Sign In</a> |
    <a href="<%= new_user_url %>"> Sign Up</a>
<% end %>
<hr>

<%= yield %>
</body>
</html>

app/views/users/new.html.erb
<h1>Sign up</h1>

  <form action="<%= users_url  %>" method="POST">
    <%= auth_token %>
    <label>Username
      <input type="text" name="user[username]">
    </label>
    <label>Password
      <input type="text" name="user[password]">
    </label>

    <button value="submit">Sign Up</button>
  </form>